//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   UPDATE BOOK_STATUS SET EXISTENTIAL_STATUS=0 WHERE BOOK_ID=&apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteBook {
            get {
                return ResourceManager.GetString("DeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INSERT INTO BOOK_MASTER VALUES(&apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;, datetime(&apos;{3}&apos;), &apos;{4}&apos;, &apos;{5}&apos;, &apos;{6}&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertBookMaster {
            get {
                return ResourceManager.GetString("InsertBookMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INSERT INTO BOOK_STATUS VALUES(&apos;{0}&apos;, 0, 1, &apos;001&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertBookStatus {
            get {
                return ResourceManager.GetString("InsertBookStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT  
        ///    BOOK_ID as &apos;ID&apos;,  
        ///    BOOK_NAME as &apos;タイトル&apos;,  
        ///    DIVISION_NAME1 as &apos;分類1&apos;, 
        ///    DIVISION_NAME2 as &apos;分類2&apos;, 
        ///    DIVISION_NAME3 as &apos;分類3&apos;, 
        ///    USER_MASTER.USER_NAME as &apos;入荷者&apos;, 
        ///    ARRIVAL_DATE as &apos;入荷日&apos;  
        ///FROM  
        ///    (SELECT *, BOOK_GENRE_MASTER.DIVISION_NAME as &apos;DIVISION_NAME3&apos;  
        ///    FROM  
        ///        (SELECT *, BOOK_GENRE_MASTER.DIVISION_NAME as &apos;DIVISION_NAME2&apos;  
        ///        FROM  
        ///            (SELECT *, BOOK_GENRE_MASTER.DIVISION_NAME as &apos;DIVISION_NAME1&apos;  
        ///            FROM  
        ///             [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectBCMT0101 {
            get {
                return ResourceManager.GetString("SelectBCMT0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AND DIVISION_ID1 = &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectBCMT0101_category1 {
            get {
                return ResourceManager.GetString("SelectBCMT0101_category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AND DIVISION_ID2 = &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectBCMT0101_category2 {
            get {
                return ResourceManager.GetString("SelectBCMT0101_category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AND DIVISION_ID3 = &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectBCMT0101_category3 {
            get {
                return ResourceManager.GetString("SelectBCMT0101_category3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   	SELECT DIVISION_ID FROM BOOK_GENRE_MASTER WHERE DIVISION_NAME=&apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectGenreId {
            get {
                return ResourceManager.GetString("SelectGenreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT VALUE FROM SYSTEM_DEFINE_MASTER WHERE VALUE=&apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectPassword {
            get {
                return ResourceManager.GetString("SelectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT USER_ID FROM USER_MASTER WHERE USER_NAME=&apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectUserId {
            get {
                return ResourceManager.GetString("SelectUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPDATE
        ///	BOOK_MASTER
        ///SET
        ///	BOOK_NAME=&apos;{0}&apos;
        ///	, ARRIVAL_USER_ID=&apos;{1}&apos;
        ///	, ARRIVAL_DATE=Datetime(&apos;{2}&apos;)
        ///	, DIVISION_ID1=&apos;{3}&apos;
        ///	, DIVISION_ID2=&apos;{4}&apos;
        ///	, DIVISION_ID3=&apos;{5}&apos;
        ///WHERE
        ///	BOOK_ID=&apos;{6}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateBookMaster {
            get {
                return ResourceManager.GetString("UpdateBookMaster", resourceCulture);
            }
        }
    }
}
